maintainer        "Jose Diaz-Gonzalez"
maintainer_email  "support@savant.be"
license           "MIT"
description       "Installs and maintains php and php modules"

depends           "nginx"

recipe            "php::module_apc", "Install the php5-apc package"
recipe            "php::module_curl", "Install the php5-curl package"
recipe            "php::module_fileinfo", "Install the php5-fileinfo package"
recipe            "php::module_fpdf", "Install the php-fpdf package"
recipe            "php::module_gd", "Install the php5-gd package"
recipe            "php::module_ldap", "Install the php5-ldap package"
recipe            "php::module_memcache", "Install the php5-memcache package"
recipe            "php::module_mongodb", "Install the mongo PECL module"
recipe            "php::module_mysql", "Install the php5-mysql package"
recipe            "php::module_snmp", "Install the php5-snmp package"
recipe            "php::module_sqlite3", "Install the php5-sqlite3 package"
recipe            "php::pear", "Install the php-pear package"
recipe            "php::php4", "Install packages for PHP version 4"
recipe            "php::php5-cgi", "Install the php5-cgi package"
recipe            "php::php5-cgi-restart", "Restart the php5-cgi package"
recipe            "php::php5", "Install php5 packages and php.ini config file"

supports "ubuntu"
